name: layerx_generator
description: A Flutter package that auto-generates a structured LayerX directory with GetX integration, MVVM pattern, and essential services for scalable projects.
version: 2.0.2
homepage: https://github.com/Umaiir11/layerx_generator
repository: https://github.com/Umaiir11/layerx_generator
issue_tracker: https://github.com/Umaiir11/layerx_generator/issues

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  args: ^2.7.0
  path: ^1.9.1
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0

executables:
  layerx_generator: layerx_generator

topics:
  - flutter
  - getx
  - mvvm
  - codegen
  - cli
